;;; minuet-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from minuet.el

(autoload 'minuet-next-suggestion "minuet" "\
Cycle to next suggestion." t)
(autoload 'minuet-previous-suggestion "minuet" "\
Cycle to previous suggestion." t)
(autoload 'minuet-show-suggestion "minuet" "\
Show code suggestion using overlay at point." t)
(autoload 'minuet-accept-suggestion "minuet" "\
Accept the current overlay suggestion." t)
(autoload 'minuet-dismiss-suggestion "minuet" "\
Dismiss the current overlay suggestion." t)
(autoload 'minuet-accept-suggestion-line "minuet" "\
Accept N lines of the current suggestion.
When called interactively with a numeric prefix argument, accept that
many lines.  Without a prefix argument, accept only the first line.

(fn &optional N)" t)
(autoload 'minuet-accept-suggestion-word "minuet" "\
Accept N words of the current suggestion.
When called interactively with a numeric prefix argument, accept that
many words.  Without a prefix argument, accept only the first word.

(fn &optional N)" t)
(autoload 'minuet-complete-with-minibuffer "minuet" "\
Complete using minibuffer interface." t)
(autoload 'minuet-auto-suggestion-mode "minuet" "\
Toggle automatic code suggestions.

When enabled, Minuet will automatically show suggestions while you type.

This is a minor mode.  If called interactively, toggle the
`Minuet-Auto-Suggestion mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `minuet-auto-suggestion-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'minuet-configure-provider "minuet" "\
Configure a minuet provider interactively.
This command offers an interactive approach to configuring provider
settings, as an alternative to manual configuration via `setq' and
`plist-put'.  When selecting either `openai-compatible' or
`openai-fim-compatible' providers, users will be prompted to specify
their endpoint and API key." t)
(register-definition-prefixes "minuet" '("minuet-"))


;;; Generated autoloads from minuet-diff.el

(register-definition-prefixes "minuet-diff" '("minuet-diff-"))


;;; Generated autoloads from minuet-duet.el

(autoload 'minuet-duet-predict "minuet-duet" "\
Request a duet (next-edit) prediction for the region around point." t)
(autoload 'minuet-duet-apply "minuet-duet" "\
Apply the current duet prediction, replacing the editable region." t)
(autoload 'minuet-duet-dismiss "minuet-duet" "\
Dismiss the current duet prediction." t)
(autoload 'minuet-duet-auto-mode "minuet-duet" "\
Toggle automatic duet (next-edit) predictions in this buffer.

When enabled, Minuet automatically requests a next-edit prediction
shortly after you edit the buffer.  Moving the cursor without editing
never triggers a prediction When `minuet-duet-auto-enable-history' is
non-nil, enabling this mode also enables `minuet-duet-history-mode';
disabling it leaves the history mode on.

This is a minor mode.  If called interactively, toggle the
`Minuet-Duet-Auto mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `minuet-duet-auto-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "minuet-duet" '("minuet-duet-"))


;;; Generated autoloads from minuet-duet-history.el

(autoload 'minuet-duet-history-mode "minuet-duet-history" "\
Track recent edits in this buffer for duet next-edit prediction.

While enabled, edits are recorded as unified diffs, one coalesced
entry per editing burst, computed on idle by an external diff program
over temporary-file snapshots.  `minuet-duet-predict' includes the
recorded history in its prompt so the model can infer the user's
intent from what they have been doing.

This is a minor mode.  If called interactively, toggle the
`Minuet-Duet-History mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `minuet-duet-history-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "minuet-duet-history" '("minuet-duet-history-"))

;;; End of scraped data

(provide 'minuet-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; minuet-autoloads.el ends here
